workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/plex-api:main
targets:
    plexgo:
        target: go
        source: my-source
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-go-plexgo
